spring.application.name=communication-channels

## connect to PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/comm_channels_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/comm-channels/protocol/openid-connect/certs